'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CategoryFilter from "../../component/categoryHeader";
import { SelectedCategoryProvider } from "../../context/selectedCategory";
import { CategoryDataProvider } from "../../context/categoryData";

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import { useState } from "react";
import SideNavCategory from "../../component/sideNavCategory";
config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
const [showSideNavCategory,setShowSideNavCategory]=useState(false)

const onCategoryChange=(value:boolean)=>{
  setShowSideNavCategory(value)
}

  return (
    <html lang="en">
      <body className={inter.className}>
        <CategoryDataProvider>
        <SelectedCategoryProvider>
        <CategoryFilter onCategoryChange={onCategoryChange} />
        {showSideNavCategory? showSideNavCategory && <SideNavCategory onCategoryChange={onCategoryChange} />:children}

        </SelectedCategoryProvider>

        </CategoryDataProvider>
        </body>

    </html>
  );
}
